### ISSUE TITLE
example problem

### ISSUE THREAD

**Issue by Bramnouwen** [IndoorAtlas/ios-sdk-swift-examples#1]
Hi,

I am using the IndoorAtlas/ios-sdk-examples, but when I run it it seems to get stuck at the waiting for 
location data.... Can someone help me?

**Comment by ntorppa** [comment]
Hi,

Please make sure you have enough movement once positioning has started. 
Try to verify if you can get locations when starting positionin and walking in the mapped area.

Br, Niko
