### ISSUE TITLE
IALocationManager.sharedInstance() not available

### ISSUE THREAD

**Issue by haeckmaenn** [IndoorAtlas/ios-sdk-swift-examples#11]
Hi,

I just downloaded the project, installed pod file, launched workspace, set the keys and tried to build and run, but the following error occurs: "IALocationManager.sharedInstance() -> Type 'IALocationManager' has no member 'sharedInstance'". What can I do to fix?

Best regards, Michael

**Comment by toninopanen** [comment]
Hi,

Which version of Xcode are you using? And which Swift version? 

BR,
Toni

**Comment by haeckmaenn** [comment]
Hi,

I am using Xcode Version 8.2.1 and Swift Version 3.

Best regards,
Michael

**Comment by toninopanen** [comment]
Are you using IndoorAtlas SDK version 2.3.1? You can check it in Podfile.lock

Thanks,
Toni
