### ISSUE TITLE
Floop plan overlay Image rotation issue on iOS

### ISSUE THREAD

**Issue by sfcal99** [IndoorAtlas/ios-sdk-swift-examples#14]
![floorplan](https://user-images.githubusercontent.com/1901867/27206443-45baccce-526a-11e7-8414-fcab5266777d.jpeg)
The floorplan image was cropped on the display image, could you please tell me how to solve this?

**Comment by toninopanen** [comment]
Hi sfcal99,

Sorry for the long delay in response! The newest version of ios-sdk-swift-examples solves this problem. 

Thanks,
Toni
