### ISSUE TITLE
didUpdateLocations of IALocationManagerDelegate didn't call

### ISSUE THREAD

**Issue by sovannarithsok** [IndoorAtlas/ios-sdk-swift-examples#2]
I have declare IALocationManage as global variable,

```
    var indoorLocationManager = IALocationManager.sharedInstance()
```

Then

```
    indoorLocationManager.setApiKey(API_KEY, andSecret: API_SECRET)
    let shopLocation = IALocation.init(floorPlanId: FLOOR_ID)
    indoorLocationManager.location = shopLocation
    indoorLocationManager.delegate = self
    indoorLocationManager.startUpdatingLocation()
```

So what's the problem?

**Comment by ntorppa** [comment]
Hi,

For iOS device, make sure you have enough of movement to be able to get the IA locations. Walk a short while in a mapped area to get enough of movement. 
Also, are you able to test your positioning with your credentials and floorplan with our public example from git hub simply just replasing credentials and floorplan? It would be fairly easy way to check that if there´s everything ok with your credentials and map.
If still no luck, let us know and we dig deeper!

Thanks!

**Comment by sovannarithsok** [comment]
@ntorppa  Hi, I have followed your instruction but no luck (I use iPhone 6+). I launch the App when I'm walking in 20 meter, it doesn't fire at all. I also practiced your public project on github both Objective-C and Swift. I observe that the delegate of IALocationManagerDelegate didn't call. I have tried many hour to search on internet but no more document or any clue. It's a hardship for me to do the project. So please give any advice or check that issue. I'm waiting your reply. Thanks

**Comment by ntorppa** [comment]
Hi, make also sure that the ID you use as FLOOR_ID from app.indooratlas.com is not venue ID but FloorplanID. You can find the floorplanID, not under "location details" but instead of that -> next to the Floor level information on the "white box" area where your mapping details/link to map can be found!
Let me know if still any issues, thanks!

**Comment by sovannarithsok** [comment]
@ntorppa  I'm really sure I picked that ID. 
![floorplanid](https://cloud.githubusercontent.com/assets/5999202/15884542/8353ea58-2d7b-11e6-900d-a99f5356e81a.png)

But no luck.

**Comment by ntorppa** [comment]
Hi, "No map revision found" means that no generated map available for that ID.
Positioning is not possible without mapping the actual floor first.
Please, see the documentation of the mapping process here;

http://docs.indooratlas.com/quick-start-guide.html

**Comment by sovannarithsok** [comment]
@ntorppa Because of this issue that I'm not yet to generate map. Thanks you so much for your help and your cooperation. 👍
