### ISSUE TITLE
Build failed after manual 'pod install' failing and manual 'pod repo add'

### ISSUE THREAD

**Issue by alons123** [IndoorAtlas/ios-sdk-swift-examples#23]
Hi,

I cloned the ios-sdk-swift-examples repo.
Tried to run `pod install` but got:
> [!] Unable to add a source with url `git@github.com:IndoorAtlas/CocoaPods-Specs.git` named `indooratlas-1`.
> You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

So I tried to add it via `pod repo add` by running:
> pod repo add indooratlas https://github.com/IndoorAtlas/CocoaPods-Specs.git

Later I tried to build it in xcode but got 6 issues of Target Integrity, Dependency Analysis Warning  and Shell Script Invocation Error, among them:
> The file “Pods-ios-sdk-swift-examples.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/alons/swiftprojects/ios-sdk-swift-examples/example/Pods/Target Support Files/Pods-ios-sdk-swift-examples/Pods-ios-sdk-swift-examples.debug.xcconfig)
And:
> PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/alons/Library/Developer/Xcode/DerivedData/ios-sdk-swift-examples-empajsyhdbjoslgoxkwwhypngciq/Build/Intermediates/ios-sdk-swift-examples.build/Debug-iphonesimulator/ios-sdk-swift-examples.build/Script-B3F62799147A638622EA9FEC.sh
>     cd /Users/alons/swiftprojects/ios-sdk-swift-examples/example
>     /bin/sh -c /Users/alons/Library/Developer/Xcode/DerivedData/ios-sdk-swift-examples-empajsyhdbjoslgoxkwwhypngciq/Build/Intermediates/ios-sdk-swift-examples.build/Debug-iphonesimulator/ios-sdk-swift-examples.build/Script-B3F62799147A638622EA9FEC.sh
> 
> diff: /../Podfile.lock: No such file or directory
> diff: /Manifest.lock: No such file or directory
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Thank you!

**Comment by michael-martinez** [comment]
To solve, do not try the suggested hint, just replace :
`source 'git@github.com:IndoorAtlas/CocoaPods-Specs.git'`
with
`source 'https://github.com/IndoorAtlas/CocoaPods-Specs.git'`
in Podfile.
Then run `pod install` again.
(You can look at the Obj-C repo to compare Podfiles).

**Comment by Cloudef** [comment]
Fixed in 95daeea thank you

**Comment by alons123** [comment]
Great, thanks everybody!
