### ISSUE TITLE
plotroute issue

### ISSUE THREAD

**Issue by sushmithadevi9** [IndoorAtlas/ios-sdk-swift-examples#24]
route.legs.count is updating as 0 when we manually choose point of interest from pickerview.
however,through gesture route.legs.count shows more than 1 and updates blue path.Otherwise no blue path appears.

**Comment by matti-ida** [comment]
Hi,

sorry for the very late response. We would need more info to investigate further. Please check our knowledge base at https://indooratlas.freshdesk.com/support/home for further support.
Thanks.
