### ISSUE TITLE
Invalid upload config

### ISSUE THREAD

**Issue by phil-andrews** [IndoorAtlas/ios-sdk-swift-examples#25]
After reading through all the other "Waiting for location data" showing forever I understand that there needs to be a floorplanId that has been created in the web dash. However, what is unclear is whether this flooplan requires being mapped by the Android MapCreator app. Is that the case? It is imperative to create the floorplan in the web dash _and then_ map it with the [MapCreator app](https://play.google.com/store/apps/details?id=com.indooratlas.android.apps.jaywalker)?

**Recommend 1**: If that is the case I recommend a better error message than "invalid upload config"? That could be anything. Plus, it's not a print error inside the iOS app so you can't string search for it in the project to trace it down.

**Recommend 2**: It would be developer friendly to have a dummy IndoorAtlas account that these demo apps could connect to to see how things work. I do not have access to one of the Android devices specified for mapping so will have to hunt one down before I can demo the main features of this software.

Thanks for your help!

**Comment by matti-ida** [comment]
Hi,

I'm very sorry for this late response. You are correct, mapping with MapCreator2 is required.
You can see our knowledge base here to get started: https://indooratlas.freshdesk.com/support/home

Thanks for the good suggestions.
