### ISSUE TITLE
when building the app on ios devices shows a ddyl: library cannot be loaded error

### ISSUE THREAD

**Issue by NirmanKalia** [IndoorAtlas/ios-sdk-swift-examples#30]
i have git cloned the directory but somehow it is failing to load indoor atlas on iPhone

**Comment by Cloudef** [comment]
Is that all it shows? Can you check if there is more information in the device console? You can open the console from window -> devices & simulators.

**Comment by NirmanKalia** [comment]
dyld: Library not loaded: @rpath/IndoorAtlas.framework/IndoorAtlas

  Referenced from: /private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/swift-examples

  Reason: no suitable image found.  Did find:

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'


 

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'


 

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: stat() failed with errno=1

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'


 

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: stat() failed with errno=1

(lldb)

**Comment by NirmanKalia** [comment]
This what it shows

dyld: Library not loaded: @rpath/IndoorAtlas.framework/IndoorAtlas

Referenced from: /private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/swift-examples

Reason: no suitable image found. Did find:

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: stat() failed with errno=1

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: stat() failed with errno=1

(lldb)


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by NirmanKalia** [comment]
> Is that all it shows? Can you check if there is more information in the device console? You can open the console from window -> devices & simulators.

dyld: Library not loaded: @rpath/IndoorAtlas.framework/IndoorAtlas

Referenced from: /private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/swift-examples

Reason: no suitable image found. Did find:

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: stat() failed with errno=1

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: code signature invalid for '/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas'

/private/var/containers/Bundle/Application/1A9D697E-7BE9-4A7F-BCD9-464F102407BA/swift-examples.app/Frameworks/IndoorAtlas.framework/IndoorAtlas: stat() failed with errno=1

(lldb)

**Comment by Cloudef** [comment]
Code signing huh. It might be we need to re-sign the framework. Meanwhile you can try https://github.com/IndoorAtlas/ios-sdk-swift-examples/blob/master/example/Podfile changing to beta SDK here.

**Comment by NirmanKalia** [comment]
> Code signing huh. It might be we need to re-sign the framework. Meanwhile you can try https://github.com/IndoorAtlas/ios-sdk-swift-examples/blob/master/example/Podfile changing to beta SDK here.

I changed in  pod 'IndoorAtlas', '3.1.3'  to '3.2.0-beta' did not work

**Comment by NirmanKalia** [comment]
> Code signing huh. It might be we need to re-sign the framework. Meanwhile you can try https://github.com/IndoorAtlas/ios-sdk-swift-examples/blob/master/example/Podfile changing to beta SDK here.

hey just asking to check whether you have resigned the app and i am unable to use the beta or any other old version of IA so I there a way around to integrate immediatly

**Comment by Cloudef** [comment]
I think there may be some way to resign the .so maybe. I'll search around. We'll be doing future releases as static library that won't need signing.

**Comment by Cloudef** [comment]
https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830 does this match your case?

**Comment by NirmanKalia** [comment]
> [Alamofire/Alamofire#3051 (comment)](https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830) does this match your case?
No,
I am using the Apple developer account and i have already tried with use_framework! thing and replacing it. it still does not work and any previous version is also not working.

**Comment by NirmanKalia** [comment]
> I think there may be some way to resign the .so maybe. I'll search around. We'll be doing future releases as static library that won't need signing.

isn't there an immediate fix of some sort

**Comment by Cloudef** [comment]
I'll provide you a static build of the latest beta in a moment.

**Comment by NirmanKalia** [comment]
> I'll provide you a static build of the latest beta in a moment.

yeah please that would be great help

**Comment by Cloudef** [comment]
Unfortunately, there are some blockers for a static build still that cause it to not work correctly.
I tried building the examples myself with following changes and it seems to be working, however my test phone isn't on latest ios, so can't confirm that.

```diff
diff --git a/example/Podfile b/example/Podfile
index 3139bdd..b22aade 100644
--- a/example/Podfile
+++ b/example/Podfile
@@ -1,9 +1,8 @@
-use_frameworks!
-
 source 'https://github.com/CocoaPods/Specs.git'
 source 'https://github.com/IndoorAtlas/CocoaPods-Specs.git'

 target 'ios-sdk-swift-examples' do
+  use_modular_headers!

   pod 'IndoorAtlas', '3.1.3'
   pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
```

**Comment by NirmanKalia** [comment]
> Unfortunately, there are some blockers for a static build still that cause it to not work correctly.
> I tried building the examples myself with following changes and it seems to be working, however my test phone isn't on latest ios, so can't confirm that.
> 
> ```diff
> diff --git a/example/Podfile b/example/Podfile
> index 3139bdd..b22aade 100644
> --- a/example/Podfile
> +++ b/example/Podfile
> @@ -1,9 +1,8 @@
> -use_frameworks!
> -
>  source 'https://github.com/CocoaPods/Specs.git'
>  source 'https://github.com/IndoorAtlas/CocoaPods-Specs.git'
> 
>  target 'ios-sdk-swift-examples' do
> +  use_modular_headers!
> 
>    pod 'IndoorAtlas', '3.1.3'
>    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
> ```

I applied the following changes but it is failing the build showing Pods_MY_PROJECT_NAME.framework: No such file or directory exists (in target 'MY_PROJECT_NAME' from project MY_PROJECT_NAME ) but it builds with use_frameworks

**Comment by Cloudef** [comment]
Did you run `pod install` after the changes?

**Comment by NirmanKalia** [comment]
> Did you run `pod install` after the changes?

yes I did pod install it showed the above error which shows that there is a .framework missing in Build/Products/Debug-Iphoneos

**Comment by Cloudef** [comment]
Strange, it seems to work here. Just in case, you are opening the xcworkspace file instead of the xcodeproj file right?

**Comment by NirmanKalia** [comment]
I am launching from xcworksoace and after I made the suggested changes ( use_modular_headers) it still shows the  same error as in beginning i.e code signature invalid

**Comment by NirmanKalia** [comment]
> > Unfortunately, there are some blockers for a static build still that cause it to not work correctly.
> > I tried building the examples myself with following changes and it seems to be working, however my test phone isn't on latest ios, so can't confirm that.
> > ```diff
> > diff --git a/example/Podfile b/example/Podfile
> > index 3139bdd..b22aade 100644
> > --- a/example/Podfile
> > +++ b/example/Podfile
> > @@ -1,9 +1,8 @@
> > -use_frameworks!
> > -
> >  source 'https://github.com/CocoaPods/Specs.git'
> >  source 'https://github.com/IndoorAtlas/CocoaPods-Specs.git'
> > 
> >  target 'ios-sdk-swift-examples' do
> > +  use_modular_headers!
> > 
> >    pod 'IndoorAtlas', '3.1.3'
> >    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
> > ```
> 
> I applied the following changes but it is failing the build showing Pods_MY_PROJECT_NAME.framework: No such file or directory exists (in target 'MY_PROJECT_NAME' from project MY_PROJECT_NAME ) but it builds with use_frameworks

this error was probably due to another library I tried to add to the sample I have removed and the sample is as it is with the suggested changes given by you but still shows the same error as it was initially giving

**Comment by Cloudef** [comment]
[8ae6d468450dc634-indooratlas-ios-sdk-3.2.0-dev-8ae6d468-localbuild.zip](https://github.com/IndoorAtlas/ios-sdk-swift-examples/files/4230763/8ae6d468450dc634-indooratlas-ios-sdk-3.2.0-dev-8ae6d468-localbuild.zip)
I managed to produce a static version of the framework now. You should be able to use this by replacing the `IndoorAtlas.framework` inside the Pods directory with the `IndoorAtlas.framework` in the zip file. Tell me how it goes, and if it goes fine and dandy, we will be switching over to static framework for future releases.

**Comment by NirmanKalia** [comment]
Thank You Very much it worked just fine and thank you for being so responsive and helpful
