### ISSUE TITLE
Wayfing Bug in SDK

### ISSUE THREAD

**Issue by NirmanKalia** [IndoorAtlas/ios-sdk-swift-examples#31]
Hi,

- It seems like there is a bug in Indoor Atlas SDK wayfinding. I encountered it while trying to refresh the route polyline with the user's location.

- It works fine as long as the user is moving towards or away from the destination and following the polyline gets shorter or larger.

- The problem arises when the user misses a turn from the shown route. The location does update and the marker can be seen moving on the wrong path. But The IALegs remain the same and does not update with the location (checked for android and ios apps with different scenarios).

- It takes a considerable distance sometimes 30-50 m for the IARoute to update

Thanks

**Comment by jalaluhtala** [comment]
Hi,

Thanks for reporting! To further help pinpoint the problem, could you provide a trace id of a positioning session where this issue happens? You can access the trace id e.g. in Android using `IALocationManager.getExtraInfo().traceId`. Note that this requires an apikey that has the session data storage enabled.

Best regards,
Juha
IndoorAtlas

**Comment by NirmanKalia** [comment]
Hi Juha, 

Here is a traceID from the session traceId: 6abfb5ea-6a6b-11ea-b39e-2bb13352f24d.1584682108946.91638.

Thanks @jalaluhtala

**Comment by jalaluhtala** [comment]
Hi, 

Thank you for the trace id, but unfortunately the apikey you used has data storage disabled. In order for us to debug the session, you need to enable the session data storage for the used apikey (this allows the session data to be uploaded to our servers). You can enable the session data upload by logging into your account in IA web portal, then go to "My apps", find and edit your apikey (three vertical dots -> "Edit API key") and enable "Yes, store session data". 

After enabling the session data storage, you can collect a new test session and share the trace id. 

Best regards,
Juha
IndoorAtlas

**Comment by NirmanKalia** [comment]
Hi,

I did enable the session data storage. Here is the traceId: a0e3e674-6a8d-11ea-9dd2-0b0a18ef96a6.1584696765231.54199.
I hope you can access the session now.

Thanks
Nirman

**Comment by jalaluhtala** [comment]
Hi,

Thank you, I can access the session now. Based on the data I might require some more detailed information from you, so could you create a ticket to our support system: support.indooratlas.com (Freshdesk) --> create ticket. And I'll provide further information through the support system. 

Best regards,
Juha
IndoorAtlas
