### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by artemisia-absynthium** [IndoorAtlas/ios-sdk-swift-examples#41]
Hello, I can't find a way to create an account on your support portal so I'm issuing this here.

[Swift Package Manager](https://www.swift.org/package-manager/) has been the official iOS package manager for a while now and I would like to complete the transition to it, but IndoorAtlas is one of the last dependencies holding me back. Please consider adding support to SPM in your roadmap for the future.

Thank you very much!

**Comment by matti-ida** [comment]
We have SPM repo for the SDK available at https://github.com/IndoorAtlas/ios-spm

Sorry for the late reply.
