### ISSUE TITLE
Stuck on "Waiting for location data" in app and also in Indoor Atlas Positioning app in iOS.

### ISSUE THREAD

**Issue by sonibhavik** [IndoorAtlas/ios-sdk-swift-examples#42]
Hello Team,

Can you guys help me to get out from waiting for location data issue in ios swift?......I have added api key. Also created location and added floor. But when I try to run Positioning app it gets loading saying waiting for location data.

Any help would be helpful.

Thank You.

**Comment by Cloudef** [comment]
Did you map the floor using MapCreator 2? For technical support, please use https://indooratlas.freshdesk.com/support/home

**Comment by sonibhavik** [comment]
I am using IndoorAtlas Positioning app which is available in AppStore. In that app also I am getting Waiting for location data.
Is there anyother app for it which you are talking about?

**Comment by Cloudef** [comment]
You have to first fingerprint your location using MapCreator 2 before you can use IndoorAtlas SDK or the Positioning app in the location. https://indooratlas.freshdesk.com/support/solutions/articles/36000408292-quick-start-guide-deployment-checklist

**Comment by sonibhavik** [comment]
Is map creator 2 is only available in android?

**Comment by Cloudef** [comment]
Only for android, yes
