### ISSUE TITLE
Stuck on 'waiting for location data'

### ISSUE THREAD

**Issue by ghost** [IndoorAtlas/ios-sdk-swift-examples#5]
I have inserted the API keys, secret, and the floor ID. And tried running it in simulator and real device. All of the 4 demos give me an infinite loading screen of "waiting for location data..." and nothing else.

For the console output, it just says "no barometer", and thats all.

Is there something I am missing?

**Comment by toninopanen** [comment]
Hi!

It seems you have added all the necessary keys. Could you provide us with more information, such as which device are you using and which OS version? “No barometer” console output is seen if the device doesn’t have barometer.

br,
Toni

**Comment by ghost** [comment]
ios 9.3.2, iPhone 5

**Comment by toninopanen** [comment]
Okay. That shouldn't be a problem. Have you mapped the area before trying to use the examples app?

**Comment by ghost** [comment]
My bad, I did not create any path in the MapCreator. Sorry

**Comment by Premal-Khetani** [comment]
How can i map the area ? 
@tonimakkonen

**Comment by toninopanen** [comment]
@Premal-Khetani check this for more information http://docs.indooratlas.com/quick-start-guide
