### ISSUE TITLE
Initial coordinates returned are always the same

### ISSUE THREAD

**Issue by mattjung** [IndoorAtlas/ios-sdk-swift-examples#6]
Hi,

I am trying to use the SDK to grab the location of a device, however when I call startUpdatingLocation() the first coordinates returned to didUpdateLocations are always the same coordinates no matter where the device is. Then when the device moves the coordinates change accordingly. Is there a way to get the correct location of the device initially after startUpdatingLocation() is called, instead of this first false result?

Thanks
Matthew

**Comment by aiyub007** [comment]
Same Problem

**Comment by toninopanen** [comment]
Hi,

Please check this to see how the initial location is set: https://github.com/IndoorAtlas/ios-sdk-swift-examples/blob/master/example/ios-sdk-swift-examples/Examples/AppleMapsOverlayViewController.swift#L189

This informs the server that the user is most likely in the given floorplan and sets the initial location according to that.

BR,
Toni
