### ISSUE TITLE
Nice Example But Don't know How It actually works from Example.

### ISSUE THREAD

**Issue by aiyub007** [IndoorAtlas/ios-sdk-swift-examples#7]
I use my API key and Secret With Floor ID. But Always it showing loading indicator for "Waiting For Location". How to update it ?? I don't want to update then. I need to use it as simple google map. How can I use it.??? 

Thanks In Advance.

**Comment by toninopanen** [comment]
Hi aiyub007,

Did you run the examples in a real device and not in a simulator? Did you also try moving while testing the example app? 

BR,
Toni
