### ISSUE TITLE
Location Not Updating Properly

### ISSUE THREAD

**Issue by jaerith** [IndoorAtlas/ios-sdk-swift-examples#8]
Even though I'm sure that your code is fine, I'm not exactly sure why the app is not working properly for me.  After uploading my floor plan image to Atlas (which was appropriate to scale), I then uploaded two 5-minute recordings of walkthroughs, hitting 16 waypoints spread through 1100 square feet.  After the upload, I used the Indoor Atlas option to generate my map.   Now, when I compile and deploy the project onto my iPad, my floor plan does load into the AppleMapsOverlay view, and I see a blue dot representing me on the floor plan.  (The view does zoom into the floor plan image to an excessive extent, but that's not a big deal.)   However, the blue dot does not accurately depict where I am in relation to the floor plan, and as I move around, the blue dot seems to appear in random locations within the floor plan instead of where I'm actually going.  What could be the problem?  Did I not prepare the map properly?  What would you recommend in order to debug the issue?

**Comment by toninopanen** [comment]
Hi jaerith,

Could you email your apikey and floorplanid to support@indooratlas.com, so we can take a look and see where the problem might be? Sometimes you have to move for about 30 seconds before getting the correct location in iOS. 

BR,
Toni

**Comment by jaerith** [comment]
Sure, I'll do that now.   Thanks for the quick response!

**Comment by toninopanen** [comment]
It seems that the floorplan you uploaded to our website was not scaled properly over the world map. You need to adjust it to fit the real scale of your test venue and then re-generate the map and test again.  

Let us know if you are still unable to get it working.
